name: Test

on:
  # push:
  #   branches: [ main ]
  #   paths:
  #     - '**.geojson'
  pull_request:
    paths:
      - '**.geojson'

env:
  # プルリクエストのターゲットブランチ
  TARGET_BRANCH: ${{ github.base_ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      # git diffをするためにターゲットブランチをフェッチする
      - name: 'Fetch'
        run: git fetch --depth 1 origin ${TARGET_BRANCH}

      - name: 'echo'
        run: |
          echo "aaa2"
          # ターゲットブランチとHEAD間で、追加,変更されたgeojsonファイルのパスを取得してループ処理
          # for file in $(git diff origin/${TARGET_BRANCH} HEAD --diff-filter=AM --name-only -- "*.geojson") ; do
          #   echo ${file}
          # done